import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tech Innovation Club",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-full flex justify-center items-center">{children}</div>
  );
}
